"""Add indexes and column renames

Revision ID: 430f4c1ba699
Revises: e29f6c50ed12
Create Date: 2026-05-08 19:05:52.301780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430f4c1ba699'
down_revision: Union[str, Sequence[str], None] = "e29f6c50ed12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_example_id', 'example', ['id'], unique=False, schema='vocapp')
    op.create_unique_constraint(None, 'example', ['example', 'translation'], schema='vocapp')
    op.drop_constraint(op.f('lexeme_idLanguage_fkey'), 'lexeme', type_='foreignkey')
    op.create_foreign_key(None, 'lexeme', 'language', ['idLanguage'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('pronunciation_idWord_fkey'), 'pronunciation', type_='foreignkey')
    op.create_foreign_key(None, 'pronunciation', 'word', ['idWord'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.create_index('ix_review_idSense', 'review', ['idSense'], unique=False, schema='vocapp')
    op.drop_constraint(op.f('review_idSense_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'sense', ['idSense'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.alter_column('reviewlog', 'id_review', new_column_name="idReview")
    op.create_index('ix_reviewlog_idReview', 'reviewlog', ['idReview'], unique=False, schema='vocapp')
    op.drop_constraint(op.f('reviewlog_id_review_fkey'), 'reviewlog', type_='foreignkey')
    op.create_foreign_key(None, 'reviewlog', 'review', ['idReview'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.create_index('ix_sense_sense', 'sense', ['sense'], unique=False, schema='vocapp')
    op.drop_constraint(op.f('sense_idWord_fkey'), 'sense', type_='foreignkey')
    op.create_foreign_key(None, 'sense', 'word', ['idWord'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.alter_column("sense_example", "id_example", new_column_name="idExample")
    op.create_index(op.f('ix_vocapp_sense_example_idExample'), 'sense_example', ['idExample'], unique=False, schema='vocapp')
    op.create_index(op.f('ix_vocapp_sense_example_idSense'), 'sense_example', ['idSense'], unique=False, schema='vocapp')
    op.drop_constraint(op.f('sense_example_idSense_fkey'), 'sense_example', type_='foreignkey')
    op.drop_constraint(op.f('sense_example_id_example_fkey'), 'sense_example', type_='foreignkey')
    op.create_foreign_key(None, 'sense_example', 'sense', ['idSense'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.create_foreign_key(None, 'sense_example', 'example', ['idExample'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('word_idLexeme_fkey'), 'word', type_='foreignkey')
    op.create_foreign_key(None, 'word', 'lexeme', ['idLexeme'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('word_attribute_idWord_fkey'), 'word_attribute', type_='foreignkey')
    op.drop_constraint(op.f('word_attribute_idType_fkey'), 'word_attribute', type_='foreignkey')
    op.create_foreign_key(None, 'word_attribute', 'word', ['idWord'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.create_foreign_key(None, 'word_attribute', 'word_attribute_type', ['idType'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('word_attribute_type_idLanguage_fkey'), 'word_attribute_type', type_='foreignkey')
    op.create_foreign_key(None, 'word_attribute_type', 'language', ['idLanguage'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word_attribute_type', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('word_attribute_type_idLanguage_fkey'), 'word_attribute_type', 'language', ['idLanguage'], ['id'])
    op.drop_constraint(None, 'word_attribute', schema='vocapp', type_='foreignkey')
    op.drop_constraint(None, 'word_attribute', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('word_attribute_idType_fkey'), 'word_attribute', 'word_attribute_type', ['idType'], ['id'])
    op.create_foreign_key(op.f('word_attribute_idWord_fkey'), 'word_attribute', 'word', ['idWord'], ['id'])
    op.drop_constraint(None, 'word', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('word_idLexeme_fkey'), 'word', 'lexeme', ['idLexeme'], ['id'])
    op.alter_column("sense_example", "idExample", new_column_name="id_example")
    op.alter_column('reviewlog', 'idReview', new_column_name="id_review")
    op.drop_constraint(None, 'sense_example', schema='vocapp', type_='foreignkey')
    op.drop_constraint(None, 'sense_example', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('sense_example_id_example_fkey'), 'sense_example', 'example', ['id_example'], ['id'])
    op.create_foreign_key(op.f('sense_example_idSense_fkey'), 'sense_example', 'sense', ['idSense'], ['id'])
    op.drop_index(op.f('ix_vocapp_sense_example_idSense'), table_name='sense_example', schema='vocapp')
    op.drop_index(op.f('ix_vocapp_sense_example_idExample'), table_name='sense_example', schema='vocapp')
    op.drop_constraint(None, 'sense', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('sense_idWord_fkey'), 'sense', 'word', ['idWord'], ['id'])
    op.drop_index('ix_sense_sense', table_name='sense', schema='vocapp')
    op.drop_constraint(None, 'reviewlog', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('reviewlog_id_review_fkey'), 'reviewlog', 'review', ['id_review'], ['id'])
    op.drop_index('ix_reviewlog_idReview', table_name='reviewlog', schema='vocapp')
    op.drop_constraint(None, 'review', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('review_idSense_fkey'), 'review', 'sense', ['idSense'], ['id'])
    op.drop_index('ix_review_idSense', table_name='review', schema='vocapp')
    op.drop_constraint(None, 'pronunciation', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('pronunciation_idWord_fkey'), 'pronunciation', 'word', ['idWord'], ['id'])
    op.drop_constraint(None, 'lexeme', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('lexeme_idLanguage_fkey'), 'lexeme', 'language', ['idLanguage'], ['id'])
    op.drop_constraint(None, 'example', schema='vocapp', type_='unique')
    op.drop_index('ix_example_id', table_name='example', schema='vocapp')
    # ### end Alembic commands ###
