"""Removed already existing indexes (from primary keys)

Revision ID: 460f33aeebef
Revises: 430f4c1ba699
Create Date: 2026-05-08 20:08:07.399957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460f33aeebef'
down_revision: Union[str, Sequence[str], None] = '430f4c1ba699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_id'), table_name='example')
    op.drop_index(op.f('ix_lexeme_id'), table_name='lexeme')
    op.drop_constraint(op.f('lexeme_idLanguage_fkey'), 'lexeme', type_='foreignkey')
    op.create_foreign_key(None, 'lexeme', 'language', ['idLanguage'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('pronunciation_idWord_fkey'), 'pronunciation', type_='foreignkey')
    op.create_foreign_key(None, 'pronunciation', 'word', ['idWord'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.drop_constraint(op.f('review_idSense_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'sense', ['idSense'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('reviewlog_idReview_fkey'), 'reviewlog', type_='foreignkey')
    op.create_foreign_key(None, 'reviewlog', 'review', ['idReview'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_index(op.f('ix_sense_id'), table_name='sense')
    op.drop_constraint(op.f('sense_idWord_fkey'), 'sense', type_='foreignkey')
    op.create_foreign_key(None, 'sense', 'word', ['idWord'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('sense_example_idExample_fkey'), 'sense_example', type_='foreignkey')
    op.drop_constraint(op.f('sense_example_idSense_fkey'), 'sense_example', type_='foreignkey')
    op.create_foreign_key(None, 'sense_example', 'example', ['idExample'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.create_foreign_key(None, 'sense_example', 'sense', ['idSense'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_index(op.f('ix_word_id'), table_name='word')
    op.drop_constraint(op.f('word_idLexeme_fkey'), 'word', type_='foreignkey')
    op.create_foreign_key(None, 'word', 'lexeme', ['idLexeme'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('word_attribute_idWord_fkey'), 'word_attribute', type_='foreignkey')
    op.drop_constraint(op.f('word_attribute_idType_fkey'), 'word_attribute', type_='foreignkey')
    op.create_foreign_key(None, 'word_attribute', 'word_attribute_type', ['idType'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.create_foreign_key(None, 'word_attribute', 'word', ['idWord'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('word_attribute_type_idLanguage_fkey'), 'word_attribute_type', type_='foreignkey')
    op.create_foreign_key(None, 'word_attribute_type', 'language', ['idLanguage'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word_attribute_type', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('word_attribute_type_idLanguage_fkey'), 'word_attribute_type', 'language', ['idLanguage'], ['id'])
    op.drop_constraint(None, 'word_attribute', schema='vocapp', type_='foreignkey')
    op.drop_constraint(None, 'word_attribute', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('word_attribute_idType_fkey'), 'word_attribute', 'word_attribute_type', ['idType'], ['id'])
    op.create_foreign_key(op.f('word_attribute_idWord_fkey'), 'word_attribute', 'word', ['idWord'], ['id'])
    op.drop_constraint(None, 'word', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('word_idLexeme_fkey'), 'word', 'lexeme', ['idLexeme'], ['id'])
    op.create_index(op.f('ix_word_id'), 'word', ['id'], unique=False)
    op.drop_constraint(None, 'sense_example', schema='vocapp', type_='foreignkey')
    op.drop_constraint(None, 'sense_example', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('sense_example_idSense_fkey'), 'sense_example', 'sense', ['idSense'], ['id'])
    op.create_foreign_key(op.f('sense_example_idExample_fkey'), 'sense_example', 'example', ['idExample'], ['id'])
    op.drop_constraint(None, 'sense', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('sense_idWord_fkey'), 'sense', 'word', ['idWord'], ['id'])
    op.create_index(op.f('ix_sense_id'), 'sense', ['id'], unique=False)
    op.drop_constraint(None, 'reviewlog', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('reviewlog_idReview_fkey'), 'reviewlog', 'review', ['idReview'], ['id'])
    op.drop_constraint(None, 'review', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('review_idSense_fkey'), 'review', 'sense', ['idSense'], ['id'])
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    op.drop_constraint(None, 'pronunciation', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('pronunciation_idWord_fkey'), 'pronunciation', 'word', ['idWord'], ['id'])
    op.drop_constraint(None, 'lexeme', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('lexeme_idLanguage_fkey'), 'lexeme', 'language', ['idLanguage'], ['id'])
    op.create_index(op.f('ix_lexeme_id'), 'lexeme', ['id'], unique=False)
    op.create_index(op.f('ix_example_id'), 'example', ['id'], unique=False)
    # ### end Alembic commands ###
