"""First setup Postgres

Revision ID: 6d86aab3278f
Revises: 
Create Date: 2026-05-01 23:54:51.902838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d86aab3278f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('example', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('dt_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='database'
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('iso639', sa.String(length=2), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('dt_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso639'),
    sa.UniqueConstraint('language'),
    schema='database'
    )
    op.create_table('lexeme',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('id_language', sa.Integer(), nullable=False),
    sa.Column('lexeme', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('dt_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_language'], ['database.language.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lexeme', 'id_language'),
    schema='database'
    )
    op.create_index('ix_lexeme_id', 'lexeme', ['id'], unique=False, schema='database')
    op.create_index('ix_lexeme_id_language', 'lexeme', ['id_language'], unique=False, schema='database')
    op.create_index('ix_lexeme_lexeme', 'lexeme', ['lexeme'], unique=False, schema='database')
    op.create_table('word_attribute_type',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('id_language', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('dt_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_language'], ['database.language.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='database'
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('id_lexeme', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('dt_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_lexeme'], ['database.lexeme.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_lexeme', 'word'),
    schema='database'
    )
    op.create_index('ix_word_id', 'word', ['id'], unique=False, schema='database')
    op.create_index('ix_word_word', 'word', ['word'], unique=False, schema='database')
    op.create_table('pronunciation',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('id_word', sa.Integer(), nullable=False),
    sa.Column('pronunciation', sa.String(), nullable=False),
    sa.Column('dialect', sa.String(), nullable=False),
    sa.Column('dt_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_word'], ['database.word.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='database'
    )
    op.create_table('sense',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('id_word', sa.Integer(), nullable=False),
    sa.Column('pos', sa.String(), nullable=False),
    sa.Column('sense', sa.String(), nullable=False),
    sa.Column('definition', sa.String(), nullable=True),
    sa.Column('usage', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('dt_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_word'], ['database.word.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='database'
    )
    op.create_index('ix_sense_id', 'sense', ['id'], unique=False, schema='database')
    op.create_index('ix_sense_id_word', 'sense', ['id_word'], unique=False, schema='database')
    op.create_table('word_attribute',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('id_word', sa.Integer(), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('dt_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_type'], ['database.word_attribute_type.id'], ),
    sa.ForeignKeyConstraint(['id_word'], ['database.word.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='database'
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('id_sense', sa.Integer(), nullable=False),
    sa.Column('is_reverse', sa.Boolean(), nullable=False),
    sa.Column('dt_started', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_due', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('dt_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_sense'], ['database.sense.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sense', 'is_reverse'),
    schema='database'
    )
    op.create_index('ix_review_id', 'review', ['id'], unique=False, schema='database')
    op.create_table('sense_example',
    sa.Column('id_sense', sa.Integer(), nullable=False),
    sa.Column('id_example', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_example'], ['database.example.id'], ),
    sa.ForeignKeyConstraint(['id_sense'], ['database.sense.id'], ),
    sa.PrimaryKeyConstraint('id_sense', 'id_example'),
    schema='database'
    )
    op.create_table('reviewlog',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('id_review', sa.Integer(), nullable=False),
    sa.Column('dt_due', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dt_review', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('dt_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dt_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_review'], ['database.review.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='database'
    )
    op.drop_table('word_attribute')
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_lexeme_id'), table_name='lexeme')
    op.drop_index(op.f('ix_lexeme_id_language'), table_name='lexeme')
    op.drop_index(op.f('ix_lexeme_lexeme'), table_name='lexeme')
    op.drop_table('lexeme')
    op.drop_index(op.f('ix_sense_id'), table_name='sense')
    op.drop_index(op.f('ix_sense_id_word'), table_name='sense')
    op.drop_table('sense')
    op.drop_table('example')
    op.drop_table('reviewlog')
    op.drop_index(op.f('ix_word_id'), table_name='word')
    op.drop_index(op.f('ix_word_word'), table_name='word')
    op.drop_table('word')
    op.drop_table('pronunciation')
    op.drop_table('language')
    op.drop_table('word_attribute_type')
    op.drop_table('sense_example')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sense_example',
    sa.Column('id_sense', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_example', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_example'], ['example.id'], name=op.f('sense_example_id_example_fkey')),
    sa.ForeignKeyConstraint(['id_sense'], ['sense.id'], name=op.f('sense_example_id_sense_fkey')),
    sa.PrimaryKeyConstraint('id_sense', 'id_example', name=op.f('sense_example_pkey'))
    )
    op.create_table('word_attribute_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_language', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_language'], ['language.id'], name=op.f('word_attribute_type_id_language_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('word_attribute_type_pkey'))
    )
    op.create_table('language',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('iso639', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('language_pkey')),
    sa.UniqueConstraint('iso639', name=op.f('language_iso639_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('language', name=op.f('language_language_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('pronunciation',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_word', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pronunciation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dialect', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_word'], ['word.id'], name=op.f('pronunciation_id_word_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pronunciation_pkey'))
    )
    op.create_table('word',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_lexeme', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('word', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_lexeme'], ['lexeme.id'], name=op.f('word_id_lexeme_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('word_pkey')),
    sa.UniqueConstraint('id_lexeme', 'word', name=op.f('word_id_lexeme_word_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_word_word'), 'word', ['word'], unique=False)
    op.create_index(op.f('ix_word_id'), 'word', ['id'], unique=False)
    op.create_table('reviewlog',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_review', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dt_due', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('dt_review', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_review'], ['review.id'], name=op.f('reviewlog_id_review_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reviewlog_pkey'))
    )
    op.create_table('example',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('example', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('translation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('example_pkey'))
    )
    op.create_table('sense',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_word', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pos', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sense', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('definition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('usage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_word'], ['word.id'], name=op.f('sense_id_word_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sense_pkey'))
    )
    op.create_index(op.f('ix_sense_id_word'), 'sense', ['id_word'], unique=False)
    op.create_index(op.f('ix_sense_id'), 'sense', ['id'], unique=False)
    op.create_table('lexeme',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_language', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lexeme', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_language'], ['language.id'], name=op.f('lexeme_id_language_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lexeme_pkey')),
    sa.UniqueConstraint('lexeme', 'id_language', name=op.f('lexeme_lexeme_id_language_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_lexeme_lexeme'), 'lexeme', ['lexeme'], unique=False)
    op.create_index(op.f('ix_lexeme_id_language'), 'lexeme', ['id_language'], unique=False)
    op.create_index(op.f('ix_lexeme_id'), 'lexeme', ['id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_sense', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_reverse', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('dt_started', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dt_due', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dt_last_review', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('state', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('step', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lapses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_sense'], ['sense.id'], name=op.f('review_id_sense_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('review_pkey')),
    sa.UniqueConstraint('id_sense', 'is_reverse', name=op.f('review_id_sense_is_reverse_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    op.create_table('word_attribute',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_word', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_type'], ['word_attribute_type.id'], name=op.f('word_attribute_id_type_fkey')),
    sa.ForeignKeyConstraint(['id_word'], ['word.id'], name=op.f('word_attribute_id_word_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('word_attribute_pkey'))
    )
    op.drop_table('reviewlog', schema='database')
    op.drop_table('sense_example', schema='database')
    op.drop_index('ix_review_id', table_name='review', schema='database')
    op.drop_table('review', schema='database')
    op.drop_table('word_attribute', schema='database')
    op.drop_index('ix_sense_id_word', table_name='sense', schema='database')
    op.drop_index('ix_sense_id', table_name='sense', schema='database')
    op.drop_table('sense', schema='database')
    op.drop_table('pronunciation', schema='database')
    op.drop_index('ix_word_word', table_name='word', schema='database')
    op.drop_index('ix_word_id', table_name='word', schema='database')
    op.drop_table('word', schema='database')
    op.drop_table('word_attribute_type', schema='database')
    op.drop_index('ix_lexeme_lexeme', table_name='lexeme', schema='database')
    op.drop_index('ix_lexeme_id_language', table_name='lexeme', schema='database')
    op.drop_index('ix_lexeme_id', table_name='lexeme', schema='database')
    op.drop_table('lexeme', schema='database')
    op.drop_table('language', schema='database')
    op.drop_table('example', schema='database')
    # ### end Alembic commands ###
