"""Add review note column & alternative words relationship & restructure of ix, uq, etc, naming conventions

Revision ID: a267bc02d155
Revises: 6cb84975696c
Create Date: 2026-05-14 13:07:29.735037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a267bc02d155'
down_revision: Union[str, Sequence[str], None] = '6cb84975696c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('example_example_translation_key'), 'example', type_='unique')
    op.create_unique_constraint(op.f('uq_example_example_translation'), 'example', ['example', 'translation'], schema='vocapp')
    op.drop_constraint(op.f('language_iso639_key'), 'language', type_='unique')
    op.drop_constraint(op.f('language_language_key'), 'language', type_='unique')
    op.create_unique_constraint(op.f('uq_language_iso639'), 'language', ['iso639'], schema='vocapp')
    op.create_unique_constraint(op.f('uq_language_language'), 'language', ['language'], schema='vocapp')
    op.drop_index(op.f('ix_lexeme_idLanguage'), table_name='lexeme')
    op.drop_index(op.f('ix_lexeme_lexeme'), table_name='lexeme')
    op.drop_constraint(op.f('lexeme_lexeme_idLanguage_key'), 'lexeme', type_='unique')
    op.create_index(op.f('ix_vocapp_lexeme_idLanguage'), 'lexeme', ['idLanguage'], unique=False, schema='vocapp')
    op.create_index(op.f('ix_vocapp_lexeme_lexeme'), 'lexeme', ['lexeme'], unique=False, schema='vocapp')
    op.create_unique_constraint(op.f('uq_lexeme_lexeme_idLanguage'), 'lexeme', ['lexeme', 'idLanguage'], schema='vocapp')
    op.drop_constraint(op.f('lexeme_idLanguage_fkey'), 'lexeme', type_='foreignkey')
    op.create_foreign_key(op.f('lexeme_idLanguage_fkey'), 'lexeme', 'language', ['idLanguage'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('pronunciation_idWord_fkey'), 'pronunciation', type_='foreignkey')
    op.create_foreign_key(op.f('pronunciation_idWord_fkey'), 'pronunciation', 'word', ['idWord'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.add_column('review', sa.Column('note', sa.String(), nullable=True))
    op.drop_index(op.f('ix_review_idSense'), table_name='review')
    op.drop_constraint(op.f('review_idSense_typeReview_key'), 'review', type_='unique')
    op.create_index(op.f('ix_vocapp_review_idSense'), 'review', ['idSense'], unique=False, schema='vocapp')
    op.create_unique_constraint(op.f('uq_review_idSense_typeReview'), 'review', ['idSense', 'typeReview'], schema='vocapp')
    op.drop_constraint(op.f('review_idSense_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(op.f('review_idSense_fkey'), 'review', 'sense', ['idSense'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_index(op.f('ix_reviewlog_idReview'), table_name='reviewlog')
    op.create_index(op.f('ix_vocapp_reviewlog_idReview'), 'reviewlog', ['idReview'], unique=False, schema='vocapp')
    op.drop_constraint(op.f('reviewlog_idReview_fkey'), 'reviewlog', type_='foreignkey')
    op.create_foreign_key(op.f('reviewlog_idReview_fkey'), 'reviewlog', 'review', ['idReview'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_index(op.f('ix_sense_idWord'), table_name='sense')
    op.drop_index(op.f('ix_sense_sense'), table_name='sense')
    op.create_index(op.f('ix_vocapp_sense_idWord'), 'sense', ['idWord'], unique=False, schema='vocapp')
    op.create_index(op.f('ix_vocapp_sense_sense'), 'sense', ['sense'], unique=False, schema='vocapp')
    op.drop_constraint(op.f('sense_idWord_fkey'), 'sense', type_='foreignkey')
    op.create_foreign_key(op.f('sense_idWord_fkey'), 'sense', 'word', ['idWord'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('sense_example_idExample_fkey'), 'sense_example', type_='foreignkey')
    op.drop_constraint(op.f('sense_example_idSense_fkey'), 'sense_example', type_='foreignkey')
    op.create_foreign_key(op.f('sense_example_idExample_fkey'), 'sense_example', 'example', ['idExample'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.create_foreign_key(op.f('sense_example_idSense_fkey'), 'sense_example', 'sense', ['idSense'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_index(op.f('ix_word_word'), table_name='word')
    op.drop_constraint(op.f('word_idLexeme_word_key'), 'word', type_='unique')
    op.create_index(op.f('ix_vocapp_word_word'), 'word', ['word'], unique=False, schema='vocapp')
    op.create_unique_constraint(op.f('uq_word_idLexeme_word'), 'word', ['idLexeme', 'word'], schema='vocapp')
    op.drop_constraint(op.f('word_idLexeme_fkey'), 'word', type_='foreignkey')
    op.create_foreign_key(op.f('word_idLexeme_fkey'), 'word', 'lexeme', ['idLexeme'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('word_attribute_idWord_fkey'), 'word_attribute', type_='foreignkey')
    op.drop_constraint(op.f('word_attribute_idType_fkey'), 'word_attribute', type_='foreignkey')
    op.create_foreign_key(op.f('word_attribute_idWord_fkey'), 'word_attribute', 'word', ['idWord'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.create_foreign_key(op.f('word_attribute_idType_fkey'), 'word_attribute', 'word_attribute_type', ['idType'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('word_attribute_type_idLanguage_fkey'), 'word_attribute_type', type_='foreignkey')
    op.create_foreign_key(op.f('word_attribute_type_idLanguage_fkey'), 'word_attribute_type', 'language', ['idLanguage'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('word_attribute_type_idLanguage_fkey'), 'word_attribute_type', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('word_attribute_type_idLanguage_fkey'), 'word_attribute_type', 'language', ['idLanguage'], ['id'])
    op.drop_constraint(op.f('word_attribute_idType_fkey'), 'word_attribute', schema='vocapp', type_='foreignkey')
    op.drop_constraint(op.f('word_attribute_idWord_fkey'), 'word_attribute', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('word_attribute_idType_fkey'), 'word_attribute', 'word_attribute_type', ['idType'], ['id'])
    op.create_foreign_key(op.f('word_attribute_idWord_fkey'), 'word_attribute', 'word', ['idWord'], ['id'])
    op.drop_constraint(op.f('word_idLexeme_fkey'), 'word', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('word_idLexeme_fkey'), 'word', 'lexeme', ['idLexeme'], ['id'])
    op.drop_constraint(op.f('uq_word_idLexeme_word'), 'word', schema='vocapp', type_='unique')
    op.drop_index(op.f('ix_vocapp_word_word'), table_name='word', schema='vocapp')
    op.create_unique_constraint(op.f('word_idLexeme_word_key'), 'word', ['idLexeme', 'word'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_word_word'), 'word', ['word'], unique=False)
    op.drop_constraint(op.f('sense_example_idSense_fkey'), 'sense_example', schema='vocapp', type_='foreignkey')
    op.drop_constraint(op.f('sense_example_idExample_fkey'), 'sense_example', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('sense_example_idSense_fkey'), 'sense_example', 'sense', ['idSense'], ['id'])
    op.create_foreign_key(op.f('sense_example_idExample_fkey'), 'sense_example', 'example', ['idExample'], ['id'])
    op.drop_constraint(op.f('sense_idWord_fkey'), 'sense', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('sense_idWord_fkey'), 'sense', 'word', ['idWord'], ['id'])
    op.drop_index(op.f('ix_vocapp_sense_sense'), table_name='sense', schema='vocapp')
    op.drop_index(op.f('ix_vocapp_sense_idWord'), table_name='sense', schema='vocapp')
    op.create_index(op.f('ix_sense_sense'), 'sense', ['sense'], unique=False)
    op.create_index(op.f('ix_sense_idWord'), 'sense', ['idWord'], unique=False)
    op.drop_constraint(op.f('reviewlog_idReview_fkey'), 'reviewlog', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('reviewlog_idReview_fkey'), 'reviewlog', 'review', ['idReview'], ['id'])
    op.drop_index(op.f('ix_vocapp_reviewlog_idReview'), table_name='reviewlog', schema='vocapp')
    op.create_index(op.f('ix_reviewlog_idReview'), 'reviewlog', ['idReview'], unique=False)
    op.drop_constraint(op.f('review_idSense_fkey'), 'review', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('review_idSense_fkey'), 'review', 'sense', ['idSense'], ['id'])
    op.drop_constraint(op.f('uq_review_idSense_typeReview'), 'review', schema='vocapp', type_='unique')
    op.drop_index(op.f('ix_vocapp_review_idSense'), table_name='review', schema='vocapp')
    op.create_unique_constraint(op.f('review_idSense_typeReview_key'), 'review', ['idSense', 'typeReview'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_review_idSense'), 'review', ['idSense'], unique=False)
    op.drop_column('review', 'note')
    op.drop_constraint(op.f('pronunciation_idWord_fkey'), 'pronunciation', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('pronunciation_idWord_fkey'), 'pronunciation', 'word', ['idWord'], ['id'])
    op.drop_constraint(op.f('lexeme_idLanguage_fkey'), 'lexeme', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('lexeme_idLanguage_fkey'), 'lexeme', 'language', ['idLanguage'], ['id'])
    op.drop_constraint(op.f('uq_lexeme_lexeme_idLanguage'), 'lexeme', schema='vocapp', type_='unique')
    op.drop_index(op.f('ix_vocapp_lexeme_lexeme'), table_name='lexeme', schema='vocapp')
    op.drop_index(op.f('ix_vocapp_lexeme_idLanguage'), table_name='lexeme', schema='vocapp')
    op.create_unique_constraint(op.f('lexeme_lexeme_idLanguage_key'), 'lexeme', ['lexeme', 'idLanguage'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_lexeme_lexeme'), 'lexeme', ['lexeme'], unique=False)
    op.create_index(op.f('ix_lexeme_idLanguage'), 'lexeme', ['idLanguage'], unique=False)
    op.drop_constraint(op.f('uq_language_language'), 'language', schema='vocapp', type_='unique')
    op.drop_constraint(op.f('uq_language_iso639'), 'language', schema='vocapp', type_='unique')
    op.create_unique_constraint(op.f('language_language_key'), 'language', ['language'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('language_iso639_key'), 'language', ['iso639'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_example_example_translation'), 'example', schema='vocapp', type_='unique')
    op.create_unique_constraint(op.f('example_example_translation_key'), 'example', ['example', 'translation'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
