"""Switch is_reverse to type

Revision ID: beb70d94702c
Revises: e3e2b197b9fe
Create Date: 2026-05-04 21:27:38.975264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb70d94702c'
down_revision: Union[str, Sequence[str], None] = 'e3e2b197b9fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lexeme_id_language_fkey'), 'lexeme', type_='foreignkey')
    op.create_foreign_key(None, 'lexeme', 'language', ['id_language'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('pronunciation_id_word_fkey'), 'pronunciation', type_='foreignkey')
    op.create_foreign_key(None, 'pronunciation', 'word', ['id_word'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.add_column('review', sa.Column('type', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('review_id_sense_is_reverse_key'), 'review', type_='unique')
    op.create_unique_constraint(None, 'review', ['id_sense', 'type'], schema='vocapp')
    op.drop_constraint(op.f('review_id_sense_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'sense', ['id_sense'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_column('review', 'is_reverse')
    op.drop_constraint(op.f('reviewlog_id_review_fkey'), 'reviewlog', type_='foreignkey')
    op.create_foreign_key(None, 'reviewlog', 'review', ['id_review'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('sense_id_word_fkey'), 'sense', type_='foreignkey')
    op.create_foreign_key(None, 'sense', 'word', ['id_word'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('sense_example_id_example_fkey'), 'sense_example', type_='foreignkey')
    op.drop_constraint(op.f('sense_example_id_sense_fkey'), 'sense_example', type_='foreignkey')
    op.create_foreign_key(None, 'sense_example', 'sense', ['id_sense'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.create_foreign_key(None, 'sense_example', 'example', ['id_example'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('word_id_lexeme_fkey'), 'word', type_='foreignkey')
    op.create_foreign_key(None, 'word', 'lexeme', ['id_lexeme'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('word_attribute_id_type_fkey'), 'word_attribute', type_='foreignkey')
    op.drop_constraint(op.f('word_attribute_id_word_fkey'), 'word_attribute', type_='foreignkey')
    op.create_foreign_key(None, 'word_attribute', 'word_attribute_type', ['id_type'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.create_foreign_key(None, 'word_attribute', 'word', ['id_word'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    op.drop_constraint(op.f('word_attribute_type_id_language_fkey'), 'word_attribute_type', type_='foreignkey')
    op.create_foreign_key(None, 'word_attribute_type', 'language', ['id_language'], ['id'], source_schema='vocapp', referent_schema='vocapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word_attribute_type', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('word_attribute_type_id_language_fkey'), 'word_attribute_type', 'language', ['id_language'], ['id'])
    op.drop_constraint(None, 'word_attribute', schema='vocapp', type_='foreignkey')
    op.drop_constraint(None, 'word_attribute', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('word_attribute_id_word_fkey'), 'word_attribute', 'word', ['id_word'], ['id'])
    op.create_foreign_key(op.f('word_attribute_id_type_fkey'), 'word_attribute', 'word_attribute_type', ['id_type'], ['id'])
    op.drop_constraint(None, 'word', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('word_id_lexeme_fkey'), 'word', 'lexeme', ['id_lexeme'], ['id'])
    op.drop_constraint(None, 'sense_example', schema='vocapp', type_='foreignkey')
    op.drop_constraint(None, 'sense_example', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('sense_example_id_sense_fkey'), 'sense_example', 'sense', ['id_sense'], ['id'])
    op.create_foreign_key(op.f('sense_example_id_example_fkey'), 'sense_example', 'example', ['id_example'], ['id'])
    op.drop_constraint(None, 'sense', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('sense_id_word_fkey'), 'sense', 'word', ['id_word'], ['id'])
    op.drop_constraint(None, 'reviewlog', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('reviewlog_id_review_fkey'), 'reviewlog', 'review', ['id_review'], ['id'])
    op.add_column('review', sa.Column('is_reverse', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'review', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('review_id_sense_fkey'), 'review', 'sense', ['id_sense'], ['id'])
    op.drop_constraint(None, 'review', schema='vocapp', type_='unique')
    op.create_unique_constraint(op.f('review_id_sense_is_reverse_key'), 'review', ['id_sense', 'is_reverse'], postgresql_nulls_not_distinct=False)
    op.drop_column('review', 'type')
    op.drop_constraint(None, 'pronunciation', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('pronunciation_id_word_fkey'), 'pronunciation', 'word', ['id_word'], ['id'])
    op.drop_constraint(None, 'lexeme', schema='vocapp', type_='foreignkey')
    op.create_foreign_key(op.f('lexeme_id_language_fkey'), 'lexeme', 'language', ['id_language'], ['id'])
    # ### end Alembic commands ###
